backend:
  name: git-gateway
  branch: main

site_url: https://mennix-007.github.io/Inseldach-Information/
display_url: https://mennix-007.github.io/Inseldach-Information/

publish_mode: simple

media_folder: "uploads"
public_folder: "/uploads"

media_library:
  name: uploadcare

collections:
  - name: "content"
    label: "Inhalte"
    files:
      - name: "news"
        label: "Kacheln & Laufband"
        file: "news.json"
        format: "json"
        fields:
          - label: "Heute wichtig (1)"
            name: "heute1"
            widget: "string"
            required: false
          - label: "Heute wichtig (2)"
            name: "heute2"
            widget: "string"
            required: false
          - label: "Heute wichtig (3)"
            name: "heute3"
            widget: "string"
            required: false
          - label: "Heute wichtig (4)"
            name: "heute4"
            widget: "string"
            required: false

          - label: "Hinweise"
            name: "daueranzeige"
            widget: "list"
            allow_add: true
            field:
              label: "Eintrag"
              name: "item"
              widget: "string"

          - label: "Bild für heute"
            name: "daueranzeigeBild"
            widget: "image"
            required: false

          - label: "Info für längeren Zeitraum"
            name: "langzeitInfo"
            widget: "list"
            allow_add: true
            field:
              label: "Eintrag"
              name: "item"
              widget: "string"

          - label: "Laufband (Ticker)"
            name: "ticker"
            widget: "list"
            allow_add: true
            field:
              label: "Eintrag"
              name: "item"
              widget: "string"
